// ---------------------------------------------------------
// This file was generated by parol.
// Do not edit this file manually.
// Changes will be overwritten on the next build.
// ---------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Reflection;
using Parol.Runtime;
using Parol.Runtime.Scanner;

namespace PascalCs {
    // Deduced grammar types
    // Type derived for non-terminal HelloWorld
    public sealed record HelloWorld(Token HelloWorldValue);

    // Type derived for non-terminal PascalCs
    public sealed record PascalCs(PascalCsOpt PascalCsOpt);

    // Type derived for non-terminal PascalCsOpt
    public sealed record PascalCsOpt(HelloWorld HelloWorld);

    /// <summary>
    /// User actions interface for the PascalCs grammar.
    /// </summary>
    public interface IPascalCsActions : IUserActions, IProvidesValueConverter {
        /// User action for non-terminal PascalCs.
        void OnPascalCs(PascalCs arg);

        /// User action for non-terminal HelloWorld.
        void OnHelloWorld(HelloWorld arg);

    }

    /// <summary>
    /// Base class for user actions for the PascalCs grammar.
    /// </summary>
    public partial class PascalCsActions : IPascalCsActions {
        /// <inheritdoc/>
        public virtual object CallSemanticActionForProductionNumber(int productionNumber, object[] children) {
            switch (productionNumber) {
                case 0: { var value = MapPascalCs(children); OnPascalCs(value); return value; }
                case 1: return MapPascalCsOpt0(children);
                case 2: return MapPascalCsOpt1(children);
                case 3: { var value = MapHelloWorld(children); OnHelloWorld(value); return value; }
                default: throw new ArgumentException($"Invalid production number {productionNumber}");
            }
        }

        /// <inheritdoc/>
        public virtual void OnComment(Token token) { }

        /// <inheritdoc/>
        public virtual IValueConverter ValueConverter { get; } = new GeneratedValueConverter();

        private sealed class GeneratedValueConverter : IValueConverter {
            public bool TryConvert(object value, Type targetType, out object? convertedValue) {
                convertedValue = null;
                if (value == null) return false;
                var sourceType = value.GetType();
                foreach (var owner in new[] { sourceType, targetType }) {
                    foreach (var method in owner.GetMethods(BindingFlags.Public | BindingFlags.Static)) {
                        if ((method.Name == "op_Implicit" || method.Name == "op_Explicit")
                            && method.ReturnType == targetType) {
                            var parameters = method.GetParameters();
                            if (parameters.Length == 1 && parameters[0].ParameterType.IsAssignableFrom(sourceType)) {
                                convertedValue = method.Invoke(null, new[] { value });
                                return true;
                            }
                        }
                    }
                }
                var ctor = targetType.GetConstructor(new[] { sourceType });
                if (ctor != null) {
                    convertedValue = ctor.Invoke(new[] { value });
                    return true;
                }
                return false;
            }
        }

        private static TTarget ConvertValue<TTarget>(object value) {
            return RuntimeValueConverter.Convert<TTarget>(value);
        }

        /// <summary>
        /// Default implementation of user-facing action for non-terminal PascalCs.
        /// </summary>
        public virtual void OnPascalCs(PascalCs arg) { }

        /// <summary>
        /// Default implementation of user-facing action for non-terminal HelloWorld.
        /// </summary>
        public virtual void OnHelloWorld(HelloWorld arg) { }


        // Mapping method for production 0: PascalCs: PascalCsOpt /* Option */;
        private static PascalCs MapPascalCs(object[] children) {
            if (children == null) throw new ArgumentNullException(nameof(children));
            if (children.Length == 1 ) return new PascalCs((PascalCsOpt)children[0 + 0]);
            if (children.Length == 1 && children[0] is PascalCs directValue) return directValue;
            throw new InvalidOperationException("Unsupported C# mapping for production 0 (PascalCs: PascalCsOpt /* Option */;)");
        }


        // Mapping method for production 1: PascalCsOpt: HelloWorld;
        private static PascalCsOpt MapPascalCsOpt0(object[] children) {
            if (children == null) throw new ArgumentNullException(nameof(children));
            if (children.Length == 1) return new PascalCsOpt((HelloWorld)children[0]);
            if (children.Length == 1 ) return new PascalCsOpt((HelloWorld)children[0 + 0]);
            if (children.Length == 1 && children[0] is PascalCsOpt directValue) return directValue;
            throw new InvalidOperationException("Unsupported C# mapping for production 1 (PascalCsOpt: HelloWorld;)");
        }


        // Mapping method for production 2: PascalCsOpt: ;
        private static PascalCsOpt MapPascalCsOpt1(object[] children) {
            if (children == null) throw new ArgumentNullException(nameof(children));
            if (children.Length == 0) return new PascalCsOpt(default!);
            if (children.Length == 1 ) return new PascalCsOpt((HelloWorld)children[0 + 0]);
            if (children.Length == 1 && children[0] is PascalCsOpt directValue) return directValue;
            throw new InvalidOperationException("Unsupported C# mapping for production 2 (PascalCsOpt: ;)");
        }


        // Mapping method for production 3: HelloWorld: "Hello world!";
        private static HelloWorld MapHelloWorld(object[] children) {
            if (children == null) throw new ArgumentNullException(nameof(children));
            if (children.Length == 1 ) return new HelloWorld((Token)children[0 + 0]);
            if (children.Length == 1 && children[0] is HelloWorld directValue) return directValue;
            throw new InvalidOperationException("Unsupported C# mapping for production 3 (HelloWorld: \"Hello world!\";)");
        }

    }
}
