// ---------------------------------------------------------
// This file was generated by parol.
// Do not edit this file manually.
// Changes will be overwritten on the next build.
// ---------------------------------------------------------

using System;
using System.Collections.Generic;
using Parol.Runtime;
using Parol.Runtime.Scanner;

namespace PascalCs {
    /// <summary>
    /// Parser facade generated by parol for this grammar.
    /// Provides parse tables and convenience entry points.
    /// </summary>
    public class PascalCsParser {
    /// <summary>
    /// Scanner tables and helper functions generated by parol for this grammar.
    /// </summary>
    public static class PascalCsScannerData {
        /// <summary>
        /// Ordered terminal names used by scanner and parser diagnostics.
        /// </summary>
        public static readonly string[] TerminalNames = [
            "EndOfInput",
            "Newline",
            "Whitespace",
            "LineComment",
            "BlockComment",
            "HelloWorld",
            "Error",
        ];

        /// <summary>
        /// Maps an input character to its scanner character class index.
        /// </summary>
        /// <param name="c">Character to classify.</param>
        /// <returns>The class index, or <c>null</c> if no class matches.</returns>
        public static int? MatchFunction(char c) {
            var intervals = new (char Start, char End, int ClassIdx)[] {
                ('\0', '\u0008', 0),
                ('\t', '\t', 1),
                ('\n', '\n', 2),
                ('\u000b', '\u000c', 1),
                ('\r', '\r', 3),
                ('\u000e', '\u001f', 0),
                (' ', ' ', 4),
                ('!', '!', 5),
                ('"', '.', 0),
                ('/', '/', 6),
                ('0', 'G', 0),
                ('H', 'H', 7),
                ('I', 'c', 0),
                ('d', 'd', 8),
                ('e', 'e', 9),
                ('f', 'k', 0),
                ('l', 'l', 10),
                ('m', 'n', 0),
                ('o', 'o', 11),
                ('p', 'q', 0),
                ('r', 'r', 12),
                ('s', 'v', 0),
                ('w', 'w', 13),
                ('x', '\u0084', 0),
                ('\u0085', '\u0085', 1),
                ('\u0086', '\u009f', 0),
                ('\u00a0', '\u00a0', 1),
                ('\u00a1', '\u167f', 0),
                ('\u1680', '\u1680', 1),
                ('\u1681', '\u1fff', 0),
                ('\u2000', '\u200a', 1),
                ('\u200b', '\u2027', 0),
                ('\u2028', '\u2029', 1),
                ('\u202a', '\u202e', 0),
                ('\u202f', '\u202f', 1),
                ('\u2030', '\u205e', 0),
                ('\u205f', '\u205f', 1),
                ('\u2060', '\u2fff', 0),
                ('\u3000', '\u3000', 1),
                ('\u3001', '\ufffe', 0),
            };

            int low = 0, high = intervals.Length - 1;
            while (low <= high) {
                int mid = low + (high - low) / 2;
                if (c >= intervals[mid].Start && c <= intervals[mid].End) return intervals[mid].ClassIdx;
                if (c < intervals[mid].Start) high = mid - 1;
                else low = mid + 1;
            }
            return null;
        }
        /// <summary>
        /// Scanner mode table consumed by the scanner runtime.
        /// </summary>
        public static readonly ScannerMode[] ScannerModes = {
            new(
                "INITIAL",
                [
                ],
                new Dfa([
                    new DfaState(
                        [ new(11), new(17), new(18), new(19), new(17), new(11), new(12), new(13), new(11), new(11), new(11), new(11), new(11), new(11) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, new(10), null, null, null, null, null, null, null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, new(16), null, null, null, null, null, null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, new(2), null, null, null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(3), null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(6), null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(7), null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, new(1), null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, new(9), null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, new(4), null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, new(8) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(6, 4, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, new(15), null, null, null, null, null, null, null ],
                        [
                            new(6, 4, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, new(5), null, null, null, null ],
                        [
                            new(6, 4, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(3, 2, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ new(15), new(15), new(14), new(15), new(15), new(15), new(15), new(15), new(15), new(15), new(15), new(15), new(15), new(15) ],
                        [
                            new(3, 2, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(5, 3, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, new(17), null, null, new(17), null, null, null, null, null, null, null, null, null ],
                        [
                            new(2, 1, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(1, 0, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, new(18), null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(1, 0, new Lookahead.None()),
                        ]
                    ),
                ])
            ),
        };
    }


        /// <summary>
        /// Maximum lookahead k used by the generated grammar.
        /// </summary>
        public const int MaxK = 1;

        /// <summary>
        /// Ordered non-terminal names used by the parser tables.
        /// </summary>
        public static readonly string[] NonTerminalNames = [
            "HelloWorld",
            "PascalCs",
            "PascalCsOpt",
        ];

        /// <summary>
        /// Lookahead DFAs indexed by non-terminal index.
        /// </summary>
        public static readonly LookaheadDfa[] LookaheadAutomata = [
            /* 0 - "HelloWorld" */
            new(
                3,
                [
                ],
                0 // k
            ),
            /* 1 - "PascalCs" */
            new(
                0,
                [
                ],
                0 // k
            ),
            /* 2 - "PascalCsOpt" */
            new(
                -1,
                [
                    new(0, 0, 2, 2),
                    new(0, 5, 1, 1),
                ],
                1 // k
            ),
        ];

        /// <summary>
        /// Production table consumed by the LL(k) parser runtime.
        /// </summary>
        public static readonly Production[] Productions = [
            // 0 - PascalCs: PascalCsOpt /* Option */;
            new Production(
                1,
                [
                    new(ParseType.N, 2),
                ]
            ),
            // 1 - PascalCsOpt: HelloWorld;
            new Production(
                2,
                [
                    new(ParseType.N, 0),
                ]
            ),
            // 2 - PascalCsOpt: ;
            new Production(
                2,
                [
                ]
            ),
            // 3 - HelloWorld: "Hello world!";
            new Production(
                0,
                [
                    new(ParseType.T, 5),
                ]
            ),
        ];

        /// <summary>
        /// Parses input with strongly typed user actions.
        /// </summary>
        /// <param name="input">Input text to parse.</param>
        /// <param name="fileName">Logical file name used for diagnostics.</param>
        /// <param name="userActions">Typed semantic action receiver.</param>
        public static void Parse(string input, string fileName, IPascalCsActions userActions) {
            ParseInternal(input, fileName, userActions);
        }

        private static void ParseInternal(string input, string fileName, IUserActions userActions) {
            var parser = new LLKParser(
                1,
                LookaheadAutomata,
                Productions,
                PascalCsScannerData.TerminalNames,
                NonTerminalNames
            );

            var tokens = Scanner.Scan(input, fileName, PascalCsScannerData.MatchFunction, PascalCsScannerData.ScannerModes);
            parser.Parse(tokens, userActions, fileName);
        }
    }
}
